### PR TITLE
Rewrite proposal v2.0

### PR DESCRIPTION
**Pull request by richardsonlima**
Proposed rewriting for include compatibility for ZCS 8...

### CODE REVIEW

**Comment by bggo** [comment]
liandros, could you check this pull request? Good to know that we may have more help for zmbkpose...

Kind Regards?

**Comment by liandros** [comment]
Hello richardsonlima . In a initial test, of rewrite_proposal_v2.0, It is running ok on zimbra 8.0.1_GA_5438 .
Do you have any error ? Can you show me ?

**Comment by uthen** [comment]
I found error after the day i do full backup. If i delete this account backup folder and use zmbkpose -i it work properly.

# zmbkpose -i -t

2013-05-06 11:16:31 DEBUG: Geting accounts in order of need backup.
2013-05-06 11:16:32 DEBUG: Testing ldapserver ldap://172.16.0.241:389, using user uid=zimbra,cn=admins,cn=zimbra
2013-05-06 11:16:32 DEBUG: Analizing 310 accounts
2013-05-06 11:16:32 DEBUG: virus-quarantine.8khvxx8d@domain.com - No previous inc. backup. Doing FULL...
2013-05-06 11:16:32 DEBUG: virus-quarantine.8khvxx8d@domain.com - START FULL backup ...
2013-05-06 11:16:32 DEBUG: virus-quarantine.8khvxx8d@domain.com - Doing ldap backup ...
Invalid DN syntax (34)
Additional information: invalid DN

Now i can't do full backup and it show same error.

# zmbkpose -f

2013-05-06 11:42:19 DEBUG: Geting accounts in order of need backup.
2013-05-06 11:42:20 DEBUG: Testing ldapserver ldap://172.16.0.241:389, using user uid=zimbra,cn=admins,cn=zimbra
2013-05-06 11:42:20 DEBUG: Analizing 310 accounts
2013-05-06 11:42:20 DEBUG: virus-quarantine.8khvxx8d@domain.com - START FULL backup ...
2013-05-06 11:42:20 DEBUG: virus-quarantine.8khvxx8d@domain.com - Doing ldap backup ...
Invalid DN syntax (34)
Additional information: invalid DN

Can i skip backup this account?

**Comment by liandros** [comment]
Hello uthen.  
Is your error related to this pull (compatibility for ZCS 8) ? Please, if not, then create a new "Issue"
I do not understand the error description. 
Can you execute it with xtrace and show me?. Example : 
  env SHELLOPTS=$SHELLOPTS:xtrace zmbkpose -f

**Comment by richardsonlima** [comment]
dumping call stack

2013/5/7 Leandro Santinelli notifications@github.com

> Hello uthen.
> 
> Is your error related to this pull (compatibility for ZCS 8) ? Please, if
> not, then create a new "Issue"
> I do not understand the error description.
> Can you execute it with xtrace and show me?. Example :
> env SHELLOPTS=$SHELLOPTS:xtrace zmbkpose -f
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bggo/Zmbkpose/pull/34#issuecomment-17561714
> .

## 

## []´s

Richardson Lima - http://br.linkedin.com/in/richardsonlima
Administrador de Redes e Sistemas / IT _network and systems administrator_
- Linux User #338927

Cel.: +55 81 8555-4638 (oi)
        +55 81 9687-1061 (tim)

"Presta atenção em seus pensamentos, pois eles se tornarão palavras.
Presta atenção em tuas palavras, pois elas se tornarão atos.
Presta atenção em teus atos, pois eles se tornarão hábitos.
Presta atenção em teus hábitos, pois eles se tornarão seu caráter.
Presta atenção em teu caráter, pois ele determinará seu destino."

**Comment by uthen** [comment]
Hi
I use ZCS 8 on Ubuntu 12.04 and use Rewrite proposal v2.0

This is log.
- debug 'Analizing 311 accounts'
  ++ /bin/date '+%F %T'
- echo '2013-05-08 20:39:14 DEBUG: Analizing 311 accounts '
  2013-05-08 20:39:14 DEBUG: Analizing 311 accounts
  ++ time_cur_tt
  ++ /bin/date +%s
- init_tt=1368020354
- bk_count=0
- for account in '$accounts'
  ++ ldap_get_mailbox_atts virus-quarantine.8khvxx8d@example.com
  ++ local mailbox=virus-quarantine.8khvxx8d@example.com
  ++ local ldap_req_atts=
  ++ ldap_search '(mail=virus-quarantine.8khvxx8d@example.com)' ''
  ++ local 'ldap_filter=(mail=virus-quarantine.8khvxx8d@example.com)'
  ++ local ldap_req_atts=
  ++ local ldap_base_dn=
  ++ /usr/bin/ldapsearch -x -H ldap://172.16.0.241:389 -D uid=zimbra,cn=admins,cn=zimbra -w password -b '' -LLL '(mail=virus-quarantine.8khvxx8d@example.com)'
- '[' -z 'dn: uid=virus-quarantine.8khvxx8d,ou=people,dc=mail,dc=example,dc=co,dc
  =th
  zimbraMailMessageLifetime: 7d
  zimbraAttachmentsIndexingEnabled: FALSE
  objectClass: organizationalPerson
  objectClass: inetOrgPerson
  objectClass: zimbraAccount
  objectClass: amavisAccount
  userPassword:: e1NTSEF9Q0QvU3F6c0doRFVEMWR3ZGt0TUQvRmwwdkcwemtqRGU=
  zimbraHideInGal: TRUE
  zimbraId: efdda844-0a6a-4d8f-9ac6-6f371d1358bf
  zimbraMailStatus: enabled
  zimbraIsSystemResource: TRUE
  zimbraMailDeliveryAddress: virus-quarantine.8khvxx8d@example.com
  uid: virus-quarantine.8khvxx8d
  mail: virus-quarantine.8khvxx8d@example.com
  zimbraAccountStatus: active
  cn: virus-quarantine.8khvxx8d
  zimbraMailQuota: 0
  zimbraMailTransport: lmtp:example.com:7025
  amavisBypassSpamChecks: TRUE
  zimbraMailHost: example.com
  zimbraPasswordModifiedTime: 20120221122724Z
  description: System account for Anti-virus quarantine.
  sn: virus-quarantine.8khvxx8d
  zimbraCreateTimestamp: 20120221122724Z
  zimbraZimletUserProperties: com_zimbra_social:social_pref_SocialMailUpdateOn:t
  rue
  zimbraZimletUserProperties: com_zimbra_social:social_pref_showTweetAlertsOn:tr
  ue
  zimbraZimletUserProperties: com_zimbra_social:social_pref_tweetmemePopularIsOn
  :true
  zimbraZimletUserProperties: com_zimbra_social:social_emailLastUpdateDate:2012/
  4/23
  zimbraZimletUserProperties: com_zimbra_social:social_alertUpdateTime:133516005
  9750
  zimbraZimletUserProperties: com_zimbra_social:social_pref_dontShowWelcomeScree
  nOn:false
  zimbraZimletUserProperties: com_zimbra_social:social_pref_diggPopularIsOn:true
  zimbraZimletUserProperties: com_zimbra_social:social_pref_numberofTweetsSearch
  esToReturn:50
  zimbraZimletUserProperties: com_zimbra_social:social_pref_cardWidthList:400px
  zimbraZimletUserProperties: com_zimbra_social:social_pref_trendsPopularIsOn:tr
  ue
  zimbraZimletUserProperties: com_zimbra_social:social_pref_socializeBtnOn:false
  zimbraZimletUserProperties: com_zimbra_social:social_pref_autoShortenURLOn:tru
  e
  zimbraZimletUserProperties: com_zimbra_social:social_pref_numberofTweetsToRetu
  rn:50
  zimbraPrefGroupMailBy: message
  zimbraIsSystemAccount: TRUE
  zimbraPrefSortOrder: BDLV:,BDLV-main:subjAsc,CAL:,CLV:,CNS:,CNSRC:,CNTGT:,CV:,
  TKL:,TV:,TV-main:dateDesc' ']'
- '[' -n '' -o -n '' ']'
- '[' FULL_BACKUP = FULL_BACKUP ']'
- do_FUNCTION=backup_account
- mode=FULL
- '[' 0 = 1 ']'
- set +e
- set -e
- backup_account virus-quarantine.8khvxx8d@example.com FULL ''
- local account=virus-quarantine.8khvxx8d@example.com
- local mode=FULL
- local backup_file=
- local query=
  ++ time_cur_tt
  ++ /bin/date +%s
- local init_tt=1368020354
- local user_bk_dir=/mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com
- '[' -z '' ']'
- '[' '!' -d /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com ']'
  +++ time_cur_date_time_mark
  +++ /bin/date +%Y%m%d%H%M%S
  ++ backup_create_file /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com 20130508203914 :FULL.tar
  ++ local dir=/mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com
  ++ local fid=20130508203914
  ++ local ending=:FULL.tar
  ++ local msg=
  ++ local max_wait_sec=6
  +++ time_cur_tt
  +++ /bin/date +%s
  ++ local start_tt=1368020354
  +++ mkdir /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com.lock
  ++ msg=
  ++ '[' -f /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar ']'
  ++ touch /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar
  ++ rm -rf /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com.lock
  ++ echo /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar
- backup_file=/mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar
- trap 'if [ 0 -ne 0 ] ;then
                      [ -f /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar ] && rm -f /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar;
                fi ;
                [ -d /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar.files ] && rm -rf /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar.files;
                trap ERR;trap RETURN;trap SIGINT' ERR RETURN SIGINT
- mkdir -p /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar.files
- debug 'virus-quarantine.8khvxx8d@example.com - START FULL backup ...'
  ++ /bin/date '+%F %T'
- echo '2013-05-08 20:39:14 DEBUG: virus-quarantine.8khvxx8d@example.com - START FULL backup ... '
  2013-05-08 20:39:14 DEBUG: virus-quarantine.8khvxx8d@example.com - START FULL backup ...
- local ldap_bkf=/mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar.files/acct.ldif
- debug 'virus-quarantine.8khvxx8d@example.com - Doing ldap backup ...'
  ++ /bin/date '+%F %T'
- echo '2013-05-08 20:39:14 DEBUG: virus-quarantine.8khvxx8d@example.com - Doing ldap backup ... '
  2013-05-08 20:39:14 DEBUG: virus-quarantine.8khvxx8d@example.com - Doing ldap backup ...
- '[' -z '' ']'
- zimbra_ldap_backup virus-quarantine.8khvxx8d@example.com /mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar.files/acct.ldif
- local account=virus-quarantine.8khvxx8d@example.com
- local backup_file=/mnt/qnap120/zmbkpose/virus-quarantine.8khvxx8d@example.com/20130508203914:FULL.tar.files/acct.ldif
  ++ ldap_get_mailbox_atts virus-quarantine.8khvxx8d@example.com dn
  ++ /bin/sed -r -n -e 's/dn: (.*)/\1/p'
  ++ local mailbox=virus-quarantine.8khvxx8d@example.com
  ++ local ldap_req_atts=dn
  ++ ldap_search '(mail=virus-quarantine.8khvxx8d@example.com)' dn
  ++ local 'ldap_filter=(mail=virus-quarantine.8khvxx8d@example.com)'
  ++ local ldap_req_atts=dn
  ++ local ldap_base_dn=
  ++ /usr/bin/ldapsearch -x -H ldap://172.16.0.241:389 -D uid=zimbra,cn=admins,cn=zimbra -w password -b '' -LLL '(mail=virus-quarantine.8khvxx8d@example.com)' dn
- local ldap_dn=uid=virus-quarantine.8khvxx8d,ou=people,dc=mail,dc=example,dc=co,dc
- '[' -z uid=virus-quarantine.8khvxx8d,ou=people,dc=mail,dc=example,dc=co,dc ']'
- ldap_search '(objectclass=*)' '' uid=virus-quarantine.8khvxx8d,ou=people,dc=mail,dc=example,dc=co,dc
- local 'ldap_filter=(objectclass=*)'
- local ldap_req_atts=
- local ldap_base_dn=uid=virus-quarantine.8khvxx8d,ou=people,dc=mail,dc=example,dc=co,dc
- /usr/bin/ldapsearch -x -H ldap://172.16.0.241:389 -D uid=zimbra,cn=admins,cn=zimbra -w password -b uid=virus-quarantine.8khvxx8d,ou=people,dc=mail,dc=example,dc=co,dc -LLL '(objectclass=*)'
  Invalid DN syntax (34)
  Additional information: invalid DN
- RET=1
- set -e
- '[' 1 -eq 0 -o -n '' ']'
  root@mail:~#

**Comment by liandros** [comment]
Is strange. In the ldap search, the server return:
   quarantine.8khvxx8d,ou=people,dc=mail,dc=example,dc=co,dc
watch the end of line : ....=co,dc
It is a line in ldif format, and is posible than it continue in next line. If true, then zmbkpose has a bug, because it does not support "folded lines" in ldif format. 
Working in the bug.

**Comment by liandros** [comment]
Hello uthen.
Please... try to download and use the branch titled "issue34".
Get me a feedback if it works

**Comment by uthen** [comment]
Hello Liandros.
I try issue34 already and it work now. 
Thank you. :)

**Pull request closed without merging**
